### ISSUE TITLE
The scheduled workflow is disabled

### ISSUE THREAD

**Issue by fno2010** [ietf-github-services/activity-summary#48]
From the GitHub Actions history, I see the following warning.

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

And the last summary was generated 3 weeks ago. Is it possible to re-enable this workflow? I think it is still very helpful.

**Comment by fno2010** [comment]
Just some quick thought: to avoid the inactivity of this repo in the future, is it possible to also write the activity summary to the `gh-pages` branch of this repo?

I'm not sure how GitHub checks the repo activity. Maybe there are some other better solutions.

**Comment by mnot** [comment]
Bumped. This ususally isn't an issue, because people make PRs fairly regularly.
